Vagrant::Config.run do |config|
  config.vm.box = "testCouch"
  config.vm.provision :puppet, :options => ["--modulepath", "/vagrant/modules"]
  config.vm.share_folder("project", "/project", "..")
end
